name: Build executable
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build executable
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install xmipy and bmi_debug_gui
        run: |
          pip install https://github.com/Deltares/xmipy/zipball/develop
          pip install -e .
      - name: Install pyinstaller
        run: |
          pip install pyinstaller
      - name: Run pyinstaller
        run: |
          pyinstaller --onefile bmi_debug_gui/__main__.py --name bmigui
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist
